# Generated by Django 4.2.11 on 2024-05-04 07:39

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='año_publicacion',
            field=models.IntegerField(default=2020, validators=[biblioteca.models.validar_año_publicacion]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(help_text='Ingrese el nombre del autor', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(help_text='Ingrese el título del libro', max_length=100),
        ),
    ]
